B4J=true
Group=Handlers
ModulesStructureVersion=1
Type=Class
Version=10.5
@EndOfDesignText@
'Index handler
'Version: 3.30
Sub Class_Globals
	Private App As EndsMeet
	Private Path As String
	Private Method As String
	Private Request As ServletRequest
	Private Response As ServletResponse
End Sub

Public Sub Initialize
	App = Main.App
End Sub

Sub Handle (req As ServletRequest, resp As ServletResponse)
	Request = req
	Response = resp
	Path = Request.RequestURI
	Method = Request.Method.ToUpperCase
	If Path = "/" And Method = "GET" Then
		ShowIndexPage
	Else If Path = "/modal" Then
		If Method = "POST" Then
			ShowModal
		Else
			Response.SendError(405, "<h1>405 Method Not Allowed</h1>")
		End If
	Else
		Response.SendError(404, "<h1>404 Page Not Found</h1>")
	End If
End Sub

Private Sub ShowIndexPage
	'Dim CacheName As String = "Index Page"
	'If MC.ExistInCache(App.ctx, CacheName) = False Then
	'	MC.WriteToCache(App.ctx, CacheName, IndexPage)
	'End If
	'Dim page1 As MiniHtml = MC.ReadFromCache(App.ctx, CacheName)
	Dim page1 As MiniHtml = IndexPage
	Dim doc As MiniHtml
	doc.Initialize("doctype")
	doc.Append(page1.build)
	App.WriteHtml2(Response, doc.ToString, App.ctx)
End Sub

Public Sub IndexPage As MiniHtml
	Dim main1 As MainView
	main1.Initialize
	main1.LoadContent(ContainerContent)
	Dim page1 As MiniHtml = main1.Render
	'test prepend comment before head tag
	Dim commment As String = " Generated by MiniHTML3 "
	Dim cmt As MiniHtml = MH.CreateTag("").text($"<!--${commment}-->"$)
	page1.Children.InsertAt(0, cmt)
	Dim navbarCollapse As MiniHtml = page1.ChildById("navbarCollapse")
	Dim navitem1 As MiniHtml = navbarCollapse.child(0)
	MH.NavLinkItem("Home", "/", "bi bi-house me-2", "Home").up(navitem1)
	If App.api.EnableHelp Then MH.NavLinkItem("API", "/help", "bi bi-gear me-2", "API").up(navitem1)
	Return page1
	
	
'	Dim html1 As MiniHtml = MH.Html
'	html1.comment(" Generated by MiniHTML3 ")
'	Dim head1 As MiniHtml = MH.ResponsiveHeader.up(html1)
'	head1.SpecialTags = Array As String("") 'indent
'	MH.Title.up(head1).text("MiniHTML3 Demo")
'	'MH.FavoriteIcon("image/png", Main.App.ServerUrl & "/assets/img/favicon.png").up(head1)
'	head1.cdn("style", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css")
'	head1.cdn("script", "https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js")
'	Dim body1 As MiniHtml = MH.Body.up(html1)
'	body1.SpecialTags = Array As String("") 'indent
'	MH.H1.up(body1).text("MiniHtml")
    

	'body1.cdn("js", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js")
	'Return html1
End Sub

Private Sub ContainerContent As MiniHtml
    Dim div1 As MiniHtml = MH.Div
    div1.cls("d-flex align-items-center")
    'div1.sty("height: 100vh")
    Dim div2 As MiniHtml = MH.Div.up(div1)
    div2.sty("margin: auto")
    Dim div3 As MiniHtml = MH.Div.up(div2)
    div3.attr("id", "modals-here")
    div3.cls("modal modal-blur fade")
    div3.sty("display: none")
    div3.attr("aria-hidden", "false")
    div3.attr("tabindex", "-1")
    div3.FormatAttributes = True
    Dim div4 As MiniHtml = MH.Div.up(div3)
    div4.cls("modal-dialog modal-lg modal-dialog-centered")
    div4.attr("role", "document")
    Dim div5 As MiniHtml = MH.Div.up(div4)
    div5.cls("modal-content")
	Dim button1 As MiniHtml = MH.HxPost("/modal", "#modals-here", "")
    button1.attr("hx-trigger", "click")
    button1.attr("data-bs-toggle", "modal")
    button1.attr("data-bs-target", "#modals-here")
    button1.cls("btn btn-primary text-uppercase")
    button1.text("Open Modal")
    button1.FormatAttributes = True
	button1.multiline
	button1.up(div2)
	Return div1
End Sub

Private Sub Modal As MiniHtml
	Return MH.ContainerModalWithButton("Modal title", "Modal body text goes here.", "Close")
End Sub

Private Sub ShowModal
	App.WriteHtml(Response, Modal.build)
End Sub

'Sub GenerateModal As String
'    Dim div1 As MiniHtml = MH.Div
'    div1.cls("modal-dialog modal-lg modal-dialog-centered")
'    Dim div2 As MiniHtml = MH.Div.up(div1)
'    div2.cls("modal-content")
'    Dim div3 As MiniHtml = MH.Div.up(div2)
'    div3.cls("modal-header")
'    Dim h51 As MiniHtml = MH.H5.up(div3)
'    h51.cls("modal-title")
'    h51.text("Modal title")
'    Dim div4 As MiniHtml = MH.Div.up(div2)
'    div4.cls("modal-body")
'    Dim p1 As MiniHtml = MH.P.up(div4)
'    p1.text("Modal body text goes here.")
'    Dim div5 As MiniHtml = MH.Div.up(div2)
'    div5.cls("modal-footer")
'    Dim button1 As MiniHtml = MH.Button.up(div5)
'    button1.attr("type", "button")
'    button1.cls("btn btn-secondary text-uppercase")
'    button1.attr("data-bs-dismiss", "modal")
'    button1.text("Close")
'    Return div1.Build
'End Sub